certify: catch HTTP code 404 exception on pending confirmation
It's usually because the transaction is not yet confirmed:
CommitmentNotFoundError: 'Pending confirmation in Bitcoin blockchain'